10 REM IDE module: irc-hive-mind
20 PRINT "=== IRC Hive Mind ==="
30 PRINT "Collective IRC memory on Flynn's Grid."
40 PRINT ""
50 PRINT "Host bridges (separate terminals):"
60 PRINT "  make irc-bridge       # local #grid on gateway:6667"
70 PRINT "  make ai-bridge        # AI summaries"
80 PRINT "  make hive-push-relay  # iOS push token relay :8770"
90 PRINT ""
100 PRINT "Run full cycle:"
110 PRINT "  basic run /programs/irc-hive-mind.bas"
120 PRINT ""
130 PRINT "IRC relay modes:"
140 PRINT "  GRIDIRC_MODE=relay make irc-bridge"
150 PRINT "  GRIDIRC_MODE=znc GRIDIRC_UPSTREAM=host:6697 make irc-bridge"
160 PRINT ""
170 PRINT "Vault keys: hive_memory, hive_summary"
180 END
