10 REM wt05 -- verify ISO_RESEARCH granted
20 PRINT "=== WT05: Cap compliance ==="
30 IF GRID.CAP(32) THEN PRINT "OK: ISO_RESEARCH" ELSE PRINT "FAIL: ISO_RESEARCH"
40 PRINT "Mask: "; GRID.CAPS$
50 END
