10 REM rt02 -- identity disc recon
20 PRINT "=== RT02: Identity ==="
30 PRINT GRID.DISC.STATUS$
40 PRINT "Entity: "; GRID.DISC.ENTITY$
50 PRINT "Level:  "; GRID.DISC.LEVEL
60 PRINT "XP:     "; GRID.DISC.XP
70 PRINT "WHOAMI: "; GRID.WHOAMI$
80 END
