10 REM rt22 -- recognizer patrol control demo
20 PRINT "=== RT22: Patrol Recon ==="
30 PRINT "Before: "; GRID.RECOGNIZER.STATUS$
40 GRID.RECOGNIZER.START
50 PRINT "Started: "; GRID.RECOGNIZER.STATUS$
60 GRID.RECOGNIZER.STOP
70 PRINT "Stopped: "; GRID.RECOGNIZER.STATUS$
80 END
